Simple script to talk to meetup API and receive JWToken on sign request
senecajs/seneca-meetup-provider pull request #5
Opened 2022-10-20 20:33 UTC by christiangubana

2022-10-26 08:49 UTC, rjrodger requested changes

2022-10-26 08:49 UTC, rjrodger commented on test/live.js
> +    file: [__dirname + '/local-env.template.js'],
the template is just a template - copy to local-env.js

2022-10-26 08:49 UTC, rjrodger commented on test/live.js
> +      $YOUR_CONSUMER_KEY: String,
not fully documented, but no need for the $ prefix here - it just indicates we want to hide the var value in logging

2022-10-26 08:49 UTC, rjrodger commented on test/local-env-template.js
>  module.exports = {
revert to template, and copy this to local-env.js

2022-10-27 10:25 UTC, christiangubana commented on test/local-env-template.js
>  module.exports = {
Reverted all these changes to keep it clean and simple in live.js script.
The idea is to get the script generates JWToken when hitting the meetup API.

2022-10-28 07:56 UTC, closed without merging